### PR TITLE
#15  Add support for other languages and plugins

### PR DESCRIPTION
**Pull request by arsi-apli**
Added new interface `com.junichi11.netbeans.modules.color.codes.preview.colors.model.ColorCodesProvider`
for other languages implementations from other plugings to use as @ServiceProvider
And moved original code to `DefaultColorCodesProvider`

And basic java support for Color constants and int RGB values `JavaColorCodesProvider`:
obrazok

### CODE REVIEW

**Comment by junichi11** [comment]
I'm sorry I'm late. I'll take a look at it later. (I would like to update my plugins now, sorry...)
BTW, please don't create a PR against the master branch. Instead, please create it against the latest `nbxx` branch. I'll create `nb100` branch now. After that, I'll change from `master` to `nb100`.

Thanks!

**Comment by arsi-apli** [comment]
OK, but it is not easier to do Build Profiles for Netbeans versions, especially if you do not make version depends changes to the source codes?

**Comment by Chris2011** [comment]
Any news here?

**Comment by junichi11** [comment]
@arsi-apli I'm sorry I'm late. I wanted to change many parts. So based on your pr, I've changed them (https://github.com/junichi11/netbeans-color-codes-preview/commit/0617cf13b7a80bf3e90327a3fb09239d96d0f1ff https://github.com/junichi11/netbeans-color-codes-preview/commit/18c02b4825b52bc9829d50e247d1dade2b4925bf). I've added your username to the commit message instead of using this PR.
If there are problems, please report them to the GitHub issues.

I've published api and spi packages, but please note that I may change signatures, method names, .... i.e. it means unstable.

Thank you for your understanding!

**Pull request closed without merging**
